// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing ParameterVersion resource
public struct ParameterVersion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. [Output only] The resource name of the ParameterVersion in the
  /// format `projects/*/locations/*/parameters/*/versions/*`.
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Disabled boolean to determine if a ParameterVersion acts as a
  /// metadata only resource (payload is never returned if disabled is true). If
  /// true any calls will always default to BASIC view even if the user
  /// explicitly passes FULL view as part of the request. A render call on a
  /// disabled resource fails with an error. Default value is False.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Required. Immutable. Payload content of a ParameterVersion resource.  This
  /// is only returned when the request provides the View value of FULL (default
  /// for GET request).
  public var payload: ParameterVersionPayload? = nil

  /// Optional. Output only. [Output only] The resource name of the KMS key
  /// version used to encrypt the ParameterVersion payload. This field is
  /// populated only if the Parameter resource has customer managed encryption
  /// key (CMEK) configured.
  public var kmsKeyVersion: Swift.String? = nil

  /// Initialize a new instance of `ParameterVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParameterVersion().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.parametermanager.v1.ParameterVersion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
