// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class ParameterManagerRetry: ParameterManagerStub {
    let inner: any ParameterManagerStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ParameterManagerStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listParameters(
      request: ListParametersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListParametersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListParametersResponse
          in
          return try await self.inner.listParameters(request: r, options: o)
        })
    }

    public func getParameter(
      request: GetParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetParameterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.getParameter(request: r, options: o)
        })
    }

    public func createParameter(
      request: CreateParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateParameterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.createParameter(request: r, options: o)
        })
    }

    public func updateParameter(
      request: UpdateParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateParameterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.updateParameter(request: r, options: o)
        })
    }

    public func deleteParameter(
      request: DeleteParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteParameterRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteParameter(request: r, options: o)
        })
    }

    public func listParameterVersions(
      request: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListParameterVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse
          in
          return try await self.inner.listParameterVersions(request: r, options: o)
        })
    }

    public func getParameterVersion(
      request: GetParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetParameterVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.getParameterVersion(request: r, options: o)
        })
    }

    public func renderParameterVersion(
      request: RenderParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: RenderParameterVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse
          in
          return try await self.inner.renderParameterVersion(request: r, options: o)
        })
    }

    public func createParameterVersion(
      request: CreateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateParameterVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.createParameterVersion(request: r, options: o)
        })
    }

    public func updateParameterVersion(
      request: UpdateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateParameterVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.updateParameterVersion(request: r, options: o)
        })
    }

    public func deleteParameterVersion(
      request: DeleteParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteParameterVersionRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteParameterVersion(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
