// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ParameterManagerStub: Sendable {
    func listParameters(
      request: ListParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse

    func getParameter(
      request: GetParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    func createParameter(
      request: CreateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    func updateParameter(
      request: UpdateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    func deleteParameter(
      request: DeleteParameterRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listParameterVersions(
      request: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse

    func getParameterVersion(
      request: GetParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    func renderParameterVersion(
      request: RenderParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    func createParameterVersion(
      request: CreateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    func updateParameterVersion(
      request: UpdateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    func deleteParameterVersion(
      request: DeleteParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listTemplates(
      request: ListTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse

    func getTemplate(
      request: GetTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template

    func createTemplate(
      request: CreateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template

    func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template

    func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listTemplateVersions(
      request: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse

    func getTemplateVersion(
      request: GetTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    func createTemplateVersion(
      request: CreateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    func updateTemplateVersion(
      request: UpdateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    func deleteTemplateVersion(
      request: DeleteTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws

    func renderTemplateVersion(
      request: RenderTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
