// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleIAMV1

/// Message describing Parameter resource
public struct Parameter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. [Output only] The resource name of the Parameter in the format
  /// `projects/*/locations/*/parameters/*`.
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Specifies the format of a Parameter.
  public var format: ParameterFormat = ParameterFormat()

  /// Output only. [Output-only] policy member strings of a Google Cloud
  /// resource.
  public var policyMember: GoogleIAMV1.ResourcePolicyMember? = nil

  /// Optional. Customer managed encryption key (CMEK) to use for encrypting the
  /// Parameter Versions. If not set, the default Google-managed encryption key
  /// will be used. Cloud KMS CryptoKeys must reside in the same location as the
  /// Parameter. The expected format is
  /// `projects/*/locations/*/keyRings/*/cryptoKeys/*`.
  public var kmsKey: Swift.String? = nil

  /// Initialize a new instance of `Parameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Parameter().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.parametermanager.v1.Parameter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
