// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "ParameterManagerQuickstart")
public final class ParameterManagerClient: Clients.ParameterManagerProtocol, Sendable {
  let inner: any Clients.ParameterManagerStub

  /// Creates a new `ParameterManagerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ParameterManagerStub = try Clients.ParameterManagerTransport(options)
    inner = Clients.ParameterManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ParameterManagerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists Parameters in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_ListParameters")
  public func listParameters(
    request: ListParametersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse {
    try await self.inner.listParameters(request: request, options: options)
  }

  /// Lists Parameters in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_ListParameters")
  public func listParameters(
    byItem: ListParametersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listParameters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Parameter.
  ///
  /// @Snippet(path: "ParameterManager_GetParameter")
  public func getParameter(
    request: GetParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    try await self.inner.getParameter(request: request, options: options)
  }

  /// Creates a new Parameter in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_CreateParameter")
  public func createParameter(
    request: CreateParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    try await self.inner.createParameter(request: request, options: options)
  }

  /// Updates a single Parameter.
  ///
  /// @Snippet(path: "ParameterManager_UpdateParameter")
  public func updateParameter(
    request: UpdateParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    try await self.inner.updateParameter(request: request, options: options)
  }

  /// Deletes a single Parameter.
  ///
  /// @Snippet(path: "ParameterManager_DeleteParameter")
  public func deleteParameter(
    request: DeleteParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteParameter(request: request, options: options)
  }

  /// Lists ParameterVersions in a given project, location, and parameter.
  ///
  /// @Snippet(path: "ParameterManager_ListParameterVersions")
  public func listParameterVersions(
    request: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse {
    try await self.inner.listParameterVersions(request: request, options: options)
  }

  /// Lists ParameterVersions in a given project, location, and parameter.
  ///
  /// @Snippet(path: "ParameterManager_ListParameterVersions")
  public func listParameterVersions(
    byItem: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listParameterVersions(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_GetParameterVersion")
  public func getParameterVersion(
    request: GetParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    try await self.inner.getParameterVersion(request: request, options: options)
  }

  /// Gets rendered version of a ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_RenderParameterVersion")
  public func renderParameterVersion(
    request: RenderParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
    try await self.inner.renderParameterVersion(request: request, options: options)
  }

  /// Creates a new ParameterVersion in a given project, location, and parameter.
  ///
  /// @Snippet(path: "ParameterManager_CreateParameterVersion")
  public func createParameterVersion(
    request: CreateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    try await self.inner.createParameterVersion(request: request, options: options)
  }

  /// Updates a single ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_UpdateParameterVersion")
  public func updateParameterVersion(
    request: UpdateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    try await self.inner.updateParameterVersion(request: request, options: options)
  }

  /// Deletes a single ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_DeleteParameterVersion")
  public func deleteParameterVersion(
    request: DeleteParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteParameterVersion(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ParameterManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ParameterManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ParameterManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ParameterManagerClient`.
  ///
  /// To mock `ParameterManagerClient` change your functions to receive
  /// `some ParameterManagerProtocol` or `any ParameterManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ParameterManagerProtocol {
    /// See `ParameterManagerClient.listParameters`.
    func listParameters(request: ListParametersRequest) async throws
      -> GoogleCloudParameterManagerV1.ListParametersResponse

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      byItem: ListParametersRequest
    ) throws -> any AsyncSequence<Parameter, Swift.Error>

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Parameter, Swift.Error>

    /// See `ParameterManagerClient.getParameter`.
    func getParameter(request: GetParameterRequest) async throws
      -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.getParameter`.
    func getParameter(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.createParameter`.
    func createParameter(request: CreateParameterRequest) async throws
      -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.createParameter`.
    func createParameter(
      parent: Swift.String,
      parameter: Parameter?,
      parameterId: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.updateParameter`.
    func updateParameter(request: UpdateParameterRequest) async throws
      -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.updateParameter`.
    func updateParameter(
      parameter: Parameter?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.deleteParameter`.
    func deleteParameter(request: DeleteParameterRequest) async throws

    /// See `ParameterManagerClient.deleteParameter`.
    func deleteParameter(
      name: Swift.String,
    ) async throws

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(request: ListParameterVersionsRequest) async throws
      -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      byItem: ListParameterVersionsRequest
    ) throws -> any AsyncSequence<ParameterVersion, Swift.Error>

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ParameterVersion, Swift.Error>

    /// See `ParameterManagerClient.getParameterVersion`.
    func getParameterVersion(request: GetParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.getParameterVersion`.
    func getParameterVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.renderParameterVersion`.
    func renderParameterVersion(request: RenderParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    /// See `ParameterManagerClient.renderParameterVersion`.
    func renderParameterVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    /// See `ParameterManagerClient.createParameterVersion`.
    func createParameterVersion(request: CreateParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.createParameterVersion`.
    func createParameterVersion(
      parent: Swift.String,
      parameterVersion: ParameterVersion?,
      parameterVersionId: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.updateParameterVersion`.
    func updateParameterVersion(request: UpdateParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.updateParameterVersion`.
    func updateParameterVersion(
      parameterVersion: ParameterVersion?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.deleteParameterVersion`.
    func deleteParameterVersion(request: DeleteParameterVersionRequest) async throws

    /// See `ParameterManagerClient.deleteParameterVersion`.
    func deleteParameterVersion(
      name: Swift.String,
    ) async throws

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ParameterManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      request: ListParametersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      byItem: ListParametersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Parameter, Swift.Error>

    /// See `ParameterManagerClient.getParameter`.
    func getParameter(
      request: GetParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.createParameter`.
    func createParameter(
      request: CreateParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.updateParameter`.
    func updateParameter(
      request: UpdateParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.deleteParameter`.
    func deleteParameter(
      request: DeleteParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      request: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      byItem: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ParameterVersion, Swift.Error>

    /// See `ParameterManagerClient.getParameterVersion`.
    func getParameterVersion(
      request: GetParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.renderParameterVersion`.
    func renderParameterVersion(
      request: RenderParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    /// See `ParameterManagerClient.createParameterVersion`.
    func createParameterVersion(
      request: CreateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.updateParameterVersion`.
    func updateParameterVersion(
      request: UpdateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.deleteParameterVersion`.
    func deleteParameterVersion(
      request: DeleteParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ParameterManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.ParameterManagerProtocol {
  public func listParameters(request: ListParametersRequest) async throws
    -> GoogleCloudParameterManagerV1.ListParametersResponse
  {
    try await self.listParameters(request: request, options: .init())
  }

  public func listParameters(
    request: ListParametersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listParameters(
    byItem: ListParametersRequest
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    try self.listParameters(byItem: byItem, options: .init())
  }

  public func listParameters(
    byItem: ListParametersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listParameters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    let request = ListParametersRequest().with {
      $0.parent = parent
    }
    return try self.listParameters(byItem: request)
  }

  public func getParameter(request: GetParameterRequest) async throws
    -> GoogleCloudParameterManagerV1.Parameter
  {
    try await self.getParameter(request: request, options: .init())
  }

  public func getParameter(
    request: GetParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getParameter(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    let request = GetParameterRequest().with {
      $0.name = name
    }
    return try await self.getParameter(request: request)
  }

  public func createParameter(request: CreateParameterRequest) async throws
    -> GoogleCloudParameterManagerV1.Parameter
  {
    try await self.createParameter(request: request, options: .init())
  }

  public func createParameter(
    request: CreateParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createParameter(
    parent: Swift.String,
    parameter: Parameter?,
    parameterId: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    let request = CreateParameterRequest().with {
      $0.parent = parent
      $0.parameter = parameter
      $0.parameterId = parameterId
    }
    return try await self.createParameter(request: request)
  }

  public func updateParameter(request: UpdateParameterRequest) async throws
    -> GoogleCloudParameterManagerV1.Parameter
  {
    try await self.updateParameter(request: request, options: .init())
  }

  public func updateParameter(
    request: UpdateParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateParameter(
    parameter: Parameter?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    let request = UpdateParameterRequest().with {
      $0.parameter = parameter
      $0.updateMask = updateMask
    }
    return try await self.updateParameter(request: request)
  }

  public func deleteParameter(request: DeleteParameterRequest) async throws {
    try await self.deleteParameter(request: request, options: .init())
  }

  public func deleteParameter(
    request: DeleteParameterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteParameter(
    name: Swift.String,
  ) async throws {
    let request = DeleteParameterRequest().with {
      $0.name = name
    }
    try await self.deleteParameter(request: request)
  }

  public func listParameterVersions(request: ListParameterVersionsRequest) async throws
    -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse
  {
    try await self.listParameterVersions(request: request, options: .init())
  }

  public func listParameterVersions(
    request: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listParameterVersions(
    byItem: ListParameterVersionsRequest
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    try self.listParameterVersions(byItem: byItem, options: .init())
  }

  public func listParameterVersions(
    byItem: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listParameterVersions(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    let request = ListParameterVersionsRequest().with {
      $0.parent = parent
    }
    return try self.listParameterVersions(byItem: request)
  }

  public func getParameterVersion(request: GetParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.ParameterVersion
  {
    try await self.getParameterVersion(request: request, options: .init())
  }

  public func getParameterVersion(
    request: GetParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getParameterVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    let request = GetParameterVersionRequest().with {
      $0.name = name
    }
    return try await self.getParameterVersion(request: request)
  }

  public func renderParameterVersion(request: RenderParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse
  {
    try await self.renderParameterVersion(request: request, options: .init())
  }

  public func renderParameterVersion(
    request: RenderParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func renderParameterVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
    let request = RenderParameterVersionRequest().with {
      $0.name = name
    }
    return try await self.renderParameterVersion(request: request)
  }

  public func createParameterVersion(request: CreateParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.ParameterVersion
  {
    try await self.createParameterVersion(request: request, options: .init())
  }

  public func createParameterVersion(
    request: CreateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createParameterVersion(
    parent: Swift.String,
    parameterVersion: ParameterVersion?,
    parameterVersionId: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    let request = CreateParameterVersionRequest().with {
      $0.parent = parent
      $0.parameterVersion = parameterVersion
      $0.parameterVersionId = parameterVersionId
    }
    return try await self.createParameterVersion(request: request)
  }

  public func updateParameterVersion(request: UpdateParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.ParameterVersion
  {
    try await self.updateParameterVersion(request: request, options: .init())
  }

  public func updateParameterVersion(
    request: UpdateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateParameterVersion(
    parameterVersion: ParameterVersion?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    let request = UpdateParameterVersionRequest().with {
      $0.parameterVersion = parameterVersion
      $0.updateMask = updateMask
    }
    return try await self.updateParameterVersion(request: request)
  }

  public func deleteParameterVersion(request: DeleteParameterVersionRequest) async throws {
    try await self.deleteParameterVersion(request: request, options: .init())
  }

  public func deleteParameterVersion(
    request: DeleteParameterVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteParameterVersion(
    name: Swift.String,
  ) async throws {
    let request = DeleteParameterVersionRequest().with {
      $0.name = name
    }
    try await self.deleteParameterVersion(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
