// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ParameterManagerLogging: ParameterManagerStub {
    let inner: any ParameterManagerStub
    let logger: Logger

    public init(_ inner: any ParameterManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-parametermanager-v1"
      logger[metadataKey: "gcp.client.service"] = "parametermanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ParameterManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listParameters(
      request: ListParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listParameters",
        action: {
          (r: ListParametersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListParametersResponse
          in
          return try await self.inner.listParameters(request: r, options: o)
        })
    }

    public func getParameter(
      request: GetParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        name: "getParameter",
        action: {
          (r: GetParameterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.getParameter(request: r, options: o)
        })
    }

    public func createParameter(
      request: CreateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        name: "createParameter",
        action: {
          (r: CreateParameterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.createParameter(request: r, options: o)
        })
    }

    public func updateParameter(
      request: UpdateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateParameter",
        action: {
          (r: UpdateParameterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.updateParameter(request: r, options: o)
        })
    }

    public func deleteParameter(
      request: DeleteParameterRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteParameter",
        action: { (r: DeleteParameterRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteParameter(request: r, options: o)
        })
    }

    public func listParameterVersions(
      request: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listParameterVersions",
        action: {
          (r: ListParameterVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse
          in
          return try await self.inner.listParameterVersions(request: r, options: o)
        })
    }

    public func getParameterVersion(
      request: GetParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getParameterVersion",
        action: {
          (r: GetParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.getParameterVersion(request: r, options: o)
        })
    }

    public func renderParameterVersion(
      request: RenderParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "renderParameterVersion",
        action: {
          (r: RenderParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse
          in
          return try await self.inner.renderParameterVersion(request: r, options: o)
        })
    }

    public func createParameterVersion(
      request: CreateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "createParameterVersion",
        action: {
          (r: CreateParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.createParameterVersion(request: r, options: o)
        })
    }

    public func updateParameterVersion(
      request: UpdateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateParameterVersion",
        action: {
          (r: UpdateParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.updateParameterVersion(request: r, options: o)
        })
    }

    public func deleteParameterVersion(
      request: DeleteParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteParameterVersion",
        action: {
          (r: DeleteParameterVersionRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteParameterVersion(request: r, options: o)
        })
    }

    public func listTemplates(
      request: ListTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTemplates",
        action: {
          (r: ListTemplatesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListTemplatesResponse
          in
          return try await self.inner.listTemplates(request: r, options: o)
        })
    }

    public func getTemplate(
      request: GetTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTemplate",
        action: {
          (r: GetTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Template
          in
          return try await self.inner.getTemplate(request: r, options: o)
        })
    }

    public func createTemplate(
      request: CreateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTemplate",
        action: {
          (r: CreateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Template
          in
          return try await self.inner.createTemplate(request: r, options: o)
        })
    }

    public func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTemplate",
        action: {
          (r: UpdateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Template
          in
          return try await self.inner.updateTemplate(request: r, options: o)
        })
    }

    public func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTemplate",
        action: { (r: DeleteTemplateRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTemplate(request: r, options: o)
        })
    }

    public func listTemplateVersions(
      request: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTemplateVersions",
        action: {
          (r: ListTemplateVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse
          in
          return try await self.inner.listTemplateVersions(request: r, options: o)
        })
    }

    public func getTemplateVersion(
      request: GetTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTemplateVersion",
        action: {
          (r: GetTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.TemplateVersion
          in
          return try await self.inner.getTemplateVersion(request: r, options: o)
        })
    }

    public func createTemplateVersion(
      request: CreateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTemplateVersion",
        action: {
          (r: CreateTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.TemplateVersion
          in
          return try await self.inner.createTemplateVersion(request: r, options: o)
        })
    }

    public func updateTemplateVersion(
      request: UpdateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTemplateVersion",
        action: {
          (r: UpdateTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.TemplateVersion
          in
          return try await self.inner.updateTemplateVersion(request: r, options: o)
        })
    }

    public func deleteTemplateVersion(
      request: DeleteTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTemplateVersion",
        action: {
          (r: DeleteTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTemplateVersion(request: r, options: o)
        })
    }

    public func renderTemplateVersion(
      request: RenderTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "renderTemplateVersion",
        action: {
          (r: RenderTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse
          in
          return try await self.inner.renderTemplateVersion(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
