// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleIAMV1
@_spi(GoogleCloudInternal) import GoogleWKT

/// Message describing Parameter resource
public struct Parameter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. [Output only] The resource name of the Parameter in the format
  /// `projects/*/locations/*/parameters/*`.
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Specifies the format of a Parameter.
  public var format: ParameterFormat = ParameterFormat()

  /// Output only. [Output-only] policy member strings of a Google Cloud
  /// resource.
  public var policyMember: GoogleIAMV1.ResourcePolicyMember? = nil

  /// Optional. Customer managed encryption key (CMEK) to use for encrypting the
  /// Parameter Versions. If not set, the default Google-managed encryption key
  /// will be used. Cloud KMS CryptoKeys must reside in the same location as the
  /// Parameter. The expected format is
  /// `projects/*/locations/*/keyRings/*/cryptoKeys/*`.
  public var kmsKey: Swift.String? = nil

  /// Optional. Input only. Immutable. Tag keys and tag values that are bound to
  /// this Parameter. You must represent each item in the map as:
  /// `"<tag-key-namespaced-name>" : "<tag-value-short-name>"`.
  ///
  /// For example, a single resource can have the following tags:
  /// ```
  ///   "123/environment": "production",
  ///   "123/costCenter": "marketing",
  /// ```
  /// Tags are used to organize and group resources.
  ///
  /// Tags can be used to control policy evaluation for the resource.
  public var tags: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Parameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Parameter().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let format = CodingKeys(stringValue: "format")
    static let policyMember = CodingKeys(stringValue: "policyMember")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let tags = CodingKeys(stringValue: "tags")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "format",
      "policyMember",
      "kmsKey",
      "tags",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(ParameterFormat.self, forKey: .format) {
      self.format = value
    }
    self.policyMember = try container.decodeIfPresent(
      GoogleIAMV1.ResourcePolicyMember.self, forKey: .policyMember)
    self.kmsKey = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.format, forKey: .format)
    try container.encodeIfPresent(self.policyMember, forKey: .policyMember)
    try container.encodeIfPresent(self.kmsKey, forKey: .kmsKey)
    try container.encode(self.tags, forKey: .tags)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.parametermanager.v1.Parameter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
