// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing ParameterVersion resource
public struct ParameterVersion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. [Output only] The resource name of the ParameterVersion in the
  /// format `projects/*/locations/*/parameters/*/versions/*`.
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Disabled boolean to determine if a ParameterVersion acts as a
  /// metadata only resource (payload is never returned if disabled is true). If
  /// true any calls will always default to BASIC view even if the user
  /// explicitly passes FULL view as part of the request. A render call on a
  /// disabled resource fails with an error. Default value is False.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Required. Immutable. Payload content of a ParameterVersion resource.  This
  /// is only returned when the request provides the View value of FULL (default
  /// for GET request).
  public var payload: ParameterVersionPayload? = nil

  /// Optional. Output only. [Output only] The resource name of the KMS key
  /// version used to encrypt the ParameterVersion payload. This field is
  /// populated only if the Parameter resource has customer managed encryption
  /// key (CMEK) configured.
  public var kmsKeyVersion: Swift.String? = nil

  /// Optional. Output only. [Output only] The source of the checksum.
  public var checksumSource: ParameterVersion.ChecksumSource? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ParameterVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParameterVersion().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let disabled = CodingKeys(stringValue: "disabled")
    static let payload = CodingKeys(stringValue: "payload")
    static let kmsKeyVersion = CodingKeys(stringValue: "kmsKeyVersion")
    static let checksumSource = CodingKeys(stringValue: "checksumSource")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "disabled",
      "payload",
      "kmsKeyVersion",
      "checksumSource",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
      self.disabled = value
    }
    self.payload = try container.decodeIfPresent(ParameterVersionPayload.self, forKey: .payload)
    self.kmsKeyVersion = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyVersion)
    self.checksumSource = try container.decodeIfPresent(
      ParameterVersion.ChecksumSource.self, forKey: .checksumSource)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.disabled, forKey: .disabled)
    try container.encodeIfPresent(self.payload, forKey: .payload)
    try container.encodeIfPresent(self.kmsKeyVersion, forKey: .kmsKeyVersion)
    try container.encodeIfPresent(self.checksumSource, forKey: .checksumSource)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The source of the checksum.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ChecksumSource: Codable, Equatable, Sendable {
    /// The default / unset value.
    case unspecified
    /// The checksum was generated by the server.
    case serverGenerated
    /// The checksum was provided by the user.
    case userSpecified
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .serverGenerated: return 1
      case .userSpecified: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CHECKSUM_SOURCE_UNSPECIFIED"
      case .serverGenerated: return "SERVER_GENERATED"
      case .userSpecified: return "USER_SPECIFIED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ChecksumSource/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CHECKSUM_SOURCE_UNSPECIFIED": self = .unspecified
      case "SERVER_GENERATED": self = .serverGenerated
      case "USER_SPECIFIED": self = .userSpecified
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ChecksumSource/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .serverGenerated
      case 2: self = .userSpecified
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CHECKSUM_SOURCE_UNSPECIFIED")
      case .serverGenerated: return try container.encode("SERVER_GENERATED")
      case .userSpecified: return try container.encode("USER_SPECIFIED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.parametermanager.v1.ParameterVersion"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
