// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "ParameterManagerQuickstart")
public final class ParameterManagerClient: Clients.ParameterManagerProtocol, Sendable {
  let inner: any Clients.ParameterManagerStub

  /// Creates a new `ParameterManagerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ParameterManagerStub = try Clients.ParameterManagerTransport(options)
    inner = Clients.ParameterManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ParameterManagerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists Parameters in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_ListParameters")
  public func listParameters(
    request: ListParametersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse {
    try await self.inner.listParameters(request: request, options: options)
  }

  /// Lists Parameters in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_ListParameters")
  public func listParameters(
    byItem: ListParametersRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listParameters(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Parameter.
  ///
  /// @Snippet(path: "ParameterManager_GetParameter")
  public func getParameter(
    request: GetParameterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    try await self.inner.getParameter(request: request, options: options)
  }

  /// Creates a new Parameter in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_CreateParameter")
  public func createParameter(
    request: CreateParameterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    try await self.inner.createParameter(request: request, options: options)
  }

  /// Updates a single Parameter.
  ///
  /// @Snippet(path: "ParameterManager_UpdateParameter")
  public func updateParameter(
    request: UpdateParameterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    try await self.inner.updateParameter(request: request, options: options)
  }

  /// Deletes a single Parameter.
  ///
  /// @Snippet(path: "ParameterManager_DeleteParameter")
  public func deleteParameter(
    request: DeleteParameterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteParameter(request: request, options: options)
  }

  /// Lists ParameterVersions in a given project, location, and parameter.
  ///
  /// @Snippet(path: "ParameterManager_ListParameterVersions")
  public func listParameterVersions(
    request: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse {
    try await self.inner.listParameterVersions(request: request, options: options)
  }

  /// Lists ParameterVersions in a given project, location, and parameter.
  ///
  /// @Snippet(path: "ParameterManager_ListParameterVersions")
  public func listParameterVersions(
    byItem: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listParameterVersions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_GetParameterVersion")
  public func getParameterVersion(
    request: GetParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    try await self.inner.getParameterVersion(request: request, options: options)
  }

  /// Gets rendered version of a ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_RenderParameterVersion")
  public func renderParameterVersion(
    request: RenderParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
    try await self.inner.renderParameterVersion(request: request, options: options)
  }

  /// Creates a new ParameterVersion in a given project, location, and parameter.
  ///
  /// @Snippet(path: "ParameterManager_CreateParameterVersion")
  public func createParameterVersion(
    request: CreateParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    try await self.inner.createParameterVersion(request: request, options: options)
  }

  /// Updates a single ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_UpdateParameterVersion")
  public func updateParameterVersion(
    request: UpdateParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    try await self.inner.updateParameterVersion(request: request, options: options)
  }

  /// Deletes a single ParameterVersion.
  ///
  /// @Snippet(path: "ParameterManager_DeleteParameterVersion")
  public func deleteParameterVersion(
    request: DeleteParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteParameterVersion(request: request, options: options)
  }

  /// Lists Templates in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_ListTemplates")
  public func listTemplates(
    request: ListTemplatesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse {
    try await self.inner.listTemplates(request: request, options: options)
  }

  /// Lists Templates in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_ListTemplates")
  public func listTemplates(
    byItem: ListTemplatesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Template, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTemplates(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Template.
  ///
  /// @Snippet(path: "ParameterManager_GetTemplate")
  public func getTemplate(
    request: GetTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    try await self.inner.getTemplate(request: request, options: options)
  }

  /// Creates a new Template in a given project and location.
  ///
  /// @Snippet(path: "ParameterManager_CreateTemplate")
  public func createTemplate(
    request: CreateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    try await self.inner.createTemplate(request: request, options: options)
  }

  /// Updates a single Template.
  ///
  /// @Snippet(path: "ParameterManager_UpdateTemplate")
  public func updateTemplate(
    request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    try await self.inner.updateTemplate(request: request, options: options)
  }

  /// Deletes a single Template.
  ///
  /// @Snippet(path: "ParameterManager_DeleteTemplate")
  public func deleteTemplate(
    request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTemplate(request: request, options: options)
  }

  /// Lists TemplateVersions in a given project, location, and template.
  ///
  /// @Snippet(path: "ParameterManager_ListTemplateVersions")
  public func listTemplateVersions(
    request: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse {
    try await self.inner.listTemplateVersions(request: request, options: options)
  }

  /// Lists TemplateVersions in a given project, location, and template.
  ///
  /// @Snippet(path: "ParameterManager_ListTemplateVersions")
  public func listTemplateVersions(
    byItem: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<TemplateVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTemplateVersions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single TemplateVersion.
  ///
  /// @Snippet(path: "ParameterManager_GetTemplateVersion")
  public func getTemplateVersion(
    request: GetTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    try await self.inner.getTemplateVersion(request: request, options: options)
  }

  /// Creates a new TemplateVersion in a given project, location, and template.
  ///
  /// @Snippet(path: "ParameterManager_CreateTemplateVersion")
  public func createTemplateVersion(
    request: CreateTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    try await self.inner.createTemplateVersion(request: request, options: options)
  }

  /// Updates a single TemplateVersion.
  ///
  /// @Snippet(path: "ParameterManager_UpdateTemplateVersion")
  public func updateTemplateVersion(
    request: UpdateTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    try await self.inner.updateTemplateVersion(request: request, options: options)
  }

  /// Deletes a single TemplateVersion.
  ///
  /// @Snippet(path: "ParameterManager_DeleteTemplateVersion")
  public func deleteTemplateVersion(
    request: DeleteTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTemplateVersion(request: request, options: options)
  }

  /// Gets rendered version of a TemplateVersion.
  ///
  /// @Snippet(path: "ParameterManager_RenderTemplateVersion")
  public func renderTemplateVersion(
    request: RenderTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse {
    try await self.inner.renderTemplateVersion(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "ParameterManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "ParameterManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ParameterManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ParameterManagerClient`.
  ///
  /// To mock `ParameterManagerClient` change your functions to receive
  /// `some ParameterManagerProtocol` or `any ParameterManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ParameterManagerProtocol {
    /// See `ParameterManagerClient.listParameters`.
    func listParameters(request: ListParametersRequest) async throws
      -> GoogleCloudParameterManagerV1.ListParametersResponse

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      byItem: ListParametersRequest
    ) throws -> any AsyncSequence<Parameter, Swift.Error>

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Parameter, Swift.Error>

    /// See `ParameterManagerClient.getParameter`.
    func getParameter(request: GetParameterRequest) async throws
      -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.getParameter`.
    func getParameter(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.createParameter`.
    func createParameter(request: CreateParameterRequest) async throws
      -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.createParameter`.
    func createParameter(
      parent: Swift.String,
      parameter: Parameter?,
      parameterId: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.updateParameter`.
    func updateParameter(request: UpdateParameterRequest) async throws
      -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.updateParameter`.
    func updateParameter(
      parameter: Parameter?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.deleteParameter`.
    func deleteParameter(request: DeleteParameterRequest) async throws

    /// See `ParameterManagerClient.deleteParameter`.
    func deleteParameter(
      name: Swift.String,
    ) async throws

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(request: ListParameterVersionsRequest) async throws
      -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      byItem: ListParameterVersionsRequest
    ) throws -> any AsyncSequence<ParameterVersion, Swift.Error>

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ParameterVersion, Swift.Error>

    /// See `ParameterManagerClient.getParameterVersion`.
    func getParameterVersion(request: GetParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.getParameterVersion`.
    func getParameterVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.renderParameterVersion`.
    func renderParameterVersion(request: RenderParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    /// See `ParameterManagerClient.renderParameterVersion`.
    func renderParameterVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    /// See `ParameterManagerClient.createParameterVersion`.
    func createParameterVersion(request: CreateParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.createParameterVersion`.
    func createParameterVersion(
      parent: Swift.String,
      parameterVersion: ParameterVersion?,
      parameterVersionId: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.updateParameterVersion`.
    func updateParameterVersion(request: UpdateParameterVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.updateParameterVersion`.
    func updateParameterVersion(
      parameterVersion: ParameterVersion?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.deleteParameterVersion`.
    func deleteParameterVersion(request: DeleteParameterVersionRequest) async throws

    /// See `ParameterManagerClient.deleteParameterVersion`.
    func deleteParameterVersion(
      name: Swift.String,
    ) async throws

    /// See `ParameterManagerClient.listTemplates`.
    func listTemplates(request: ListTemplatesRequest) async throws
      -> GoogleCloudParameterManagerV1.ListTemplatesResponse

    /// See `ParameterManagerClient.listTemplates`.
    func listTemplates(
      byItem: ListTemplatesRequest
    ) throws -> any AsyncSequence<Template, Swift.Error>

    /// See `ParameterManagerClient.listTemplates`.
    func listTemplates(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Template, Swift.Error>

    /// See `ParameterManagerClient.getTemplate`.
    func getTemplate(request: GetTemplateRequest) async throws
      -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.getTemplate`.
    func getTemplate(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.createTemplate`.
    func createTemplate(request: CreateTemplateRequest) async throws
      -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.createTemplate`.
    func createTemplate(
      parent: Swift.String,
      template: Template?,
      templateId: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.updateTemplate`.
    func updateTemplate(request: UpdateTemplateRequest) async throws
      -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.updateTemplate`.
    func updateTemplate(
      template: Template?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.deleteTemplate`.
    func deleteTemplate(request: DeleteTemplateRequest) async throws

    /// See `ParameterManagerClient.deleteTemplate`.
    func deleteTemplate(
      name: Swift.String,
    ) async throws

    /// See `ParameterManagerClient.listTemplateVersions`.
    func listTemplateVersions(request: ListTemplateVersionsRequest) async throws
      -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse

    /// See `ParameterManagerClient.listTemplateVersions`.
    func listTemplateVersions(
      byItem: ListTemplateVersionsRequest
    ) throws -> any AsyncSequence<TemplateVersion, Swift.Error>

    /// See `ParameterManagerClient.listTemplateVersions`.
    func listTemplateVersions(
      parent: Swift.String,
    ) throws -> any AsyncSequence<TemplateVersion, Swift.Error>

    /// See `ParameterManagerClient.getTemplateVersion`.
    func getTemplateVersion(request: GetTemplateVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.getTemplateVersion`.
    func getTemplateVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.createTemplateVersion`.
    func createTemplateVersion(request: CreateTemplateVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.createTemplateVersion`.
    func createTemplateVersion(
      parent: Swift.String,
      templateVersion: TemplateVersion?,
      templateVersionId: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.updateTemplateVersion`.
    func updateTemplateVersion(request: UpdateTemplateVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.updateTemplateVersion`.
    func updateTemplateVersion(
      templateVersion: TemplateVersion?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.deleteTemplateVersion`.
    func deleteTemplateVersion(request: DeleteTemplateVersionRequest) async throws

    /// See `ParameterManagerClient.deleteTemplateVersion`.
    func deleteTemplateVersion(
      name: Swift.String,
    ) async throws

    /// See `ParameterManagerClient.renderTemplateVersion`.
    func renderTemplateVersion(request: RenderTemplateVersionRequest) async throws
      -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse

    /// See `ParameterManagerClient.renderTemplateVersion`.
    func renderTemplateVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ParameterManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      request: ListParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse

    /// See `ParameterManagerClient.listParameters`.
    func listParameters(
      byItem: ListParametersRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<Parameter, Swift.Error>

    /// See `ParameterManagerClient.getParameter`.
    func getParameter(
      request: GetParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.createParameter`.
    func createParameter(
      request: CreateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.updateParameter`.
    func updateParameter(
      request: UpdateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    /// See `ParameterManagerClient.deleteParameter`.
    func deleteParameter(
      request: DeleteParameterRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      request: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse

    /// See `ParameterManagerClient.listParameterVersions`.
    func listParameterVersions(
      byItem: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<ParameterVersion, Swift.Error>

    /// See `ParameterManagerClient.getParameterVersion`.
    func getParameterVersion(
      request: GetParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.renderParameterVersion`.
    func renderParameterVersion(
      request: RenderParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    /// See `ParameterManagerClient.createParameterVersion`.
    func createParameterVersion(
      request: CreateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.updateParameterVersion`.
    func updateParameterVersion(
      request: UpdateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    /// See `ParameterManagerClient.deleteParameterVersion`.
    func deleteParameterVersion(
      request: DeleteParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ParameterManagerClient.listTemplates`.
    func listTemplates(
      request: ListTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse

    /// See `ParameterManagerClient.listTemplates`.
    func listTemplates(
      byItem: ListTemplatesRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<Template, Swift.Error>

    /// See `ParameterManagerClient.getTemplate`.
    func getTemplate(
      request: GetTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.createTemplate`.
    func createTemplate(
      request: CreateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.updateTemplate`.
    func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template

    /// See `ParameterManagerClient.deleteTemplate`.
    func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ParameterManagerClient.listTemplateVersions`.
    func listTemplateVersions(
      request: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse

    /// See `ParameterManagerClient.listTemplateVersions`.
    func listTemplateVersions(
      byItem: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<TemplateVersion, Swift.Error>

    /// See `ParameterManagerClient.getTemplateVersion`.
    func getTemplateVersion(
      request: GetTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.createTemplateVersion`.
    func createTemplateVersion(
      request: CreateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.updateTemplateVersion`.
    func updateTemplateVersion(
      request: UpdateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion

    /// See `ParameterManagerClient.deleteTemplateVersion`.
    func deleteTemplateVersion(
      request: DeleteTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ParameterManagerClient.renderTemplateVersion`.
    func renderTemplateVersion(
      request: RenderTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ParameterManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ParameterManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.ParameterManagerProtocol {
  public func listParameters(request: ListParametersRequest) async throws
    -> GoogleCloudParameterManagerV1.ListParametersResponse
  {
    try await self.listParameters(request: request, options: .init())
  }

  public func listParameters(
    request: ListParametersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listParameters(
    byItem: ListParametersRequest
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    try self.listParameters(byItem: byItem, options: .init())
  }

  public func listParameters(
    byItem: ListParametersRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listParameters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Parameter, Swift.Error> {
    let request = ListParametersRequest().with {
      $0.parent = parent
    }
    return try self.listParameters(byItem: request)
  }

  public func getParameter(request: GetParameterRequest) async throws
    -> GoogleCloudParameterManagerV1.Parameter
  {
    try await self.getParameter(request: request, options: .init())
  }

  public func getParameter(
    request: GetParameterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getParameter(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    let request = GetParameterRequest().with {
      $0.name = name
    }
    return try await self.getParameter(request: request)
  }

  public func createParameter(request: CreateParameterRequest) async throws
    -> GoogleCloudParameterManagerV1.Parameter
  {
    try await self.createParameter(request: request, options: .init())
  }

  public func createParameter(
    request: CreateParameterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createParameter(
    parent: Swift.String,
    parameter: Parameter?,
    parameterId: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    let request = CreateParameterRequest().with {
      $0.parent = parent
      $0.parameter = parameter
      $0.parameterId = parameterId
    }
    return try await self.createParameter(request: request)
  }

  public func updateParameter(request: UpdateParameterRequest) async throws
    -> GoogleCloudParameterManagerV1.Parameter
  {
    try await self.updateParameter(request: request, options: .init())
  }

  public func updateParameter(
    request: UpdateParameterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateParameter(
    parameter: Parameter?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleCloudParameterManagerV1.Parameter {
    let request = UpdateParameterRequest().with {
      $0.parameter = parameter
      $0.updateMask = updateMask
    }
    return try await self.updateParameter(request: request)
  }

  public func deleteParameter(request: DeleteParameterRequest) async throws {
    try await self.deleteParameter(request: request, options: .init())
  }

  public func deleteParameter(
    request: DeleteParameterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteParameter(
    name: Swift.String,
  ) async throws {
    let request = DeleteParameterRequest().with {
      $0.name = name
    }
    try await self.deleteParameter(request: request)
  }

  public func listParameterVersions(request: ListParameterVersionsRequest) async throws
    -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse
  {
    try await self.listParameterVersions(request: request, options: .init())
  }

  public func listParameterVersions(
    request: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listParameterVersions(
    byItem: ListParameterVersionsRequest
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    try self.listParameterVersions(byItem: byItem, options: .init())
  }

  public func listParameterVersions(
    byItem: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listParameterVersions(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ParameterVersion, Swift.Error> {
    let request = ListParameterVersionsRequest().with {
      $0.parent = parent
    }
    return try self.listParameterVersions(byItem: request)
  }

  public func getParameterVersion(request: GetParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.ParameterVersion
  {
    try await self.getParameterVersion(request: request, options: .init())
  }

  public func getParameterVersion(
    request: GetParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getParameterVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    let request = GetParameterVersionRequest().with {
      $0.name = name
    }
    return try await self.getParameterVersion(request: request)
  }

  public func renderParameterVersion(request: RenderParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse
  {
    try await self.renderParameterVersion(request: request, options: .init())
  }

  public func renderParameterVersion(
    request: RenderParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func renderParameterVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
    let request = RenderParameterVersionRequest().with {
      $0.name = name
    }
    return try await self.renderParameterVersion(request: request)
  }

  public func createParameterVersion(request: CreateParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.ParameterVersion
  {
    try await self.createParameterVersion(request: request, options: .init())
  }

  public func createParameterVersion(
    request: CreateParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createParameterVersion(
    parent: Swift.String,
    parameterVersion: ParameterVersion?,
    parameterVersionId: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    let request = CreateParameterVersionRequest().with {
      $0.parent = parent
      $0.parameterVersion = parameterVersion
      $0.parameterVersionId = parameterVersionId
    }
    return try await self.createParameterVersion(request: request)
  }

  public func updateParameterVersion(request: UpdateParameterVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.ParameterVersion
  {
    try await self.updateParameterVersion(request: request, options: .init())
  }

  public func updateParameterVersion(
    request: UpdateParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateParameterVersion(
    parameterVersion: ParameterVersion?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
    let request = UpdateParameterVersionRequest().with {
      $0.parameterVersion = parameterVersion
      $0.updateMask = updateMask
    }
    return try await self.updateParameterVersion(request: request)
  }

  public func deleteParameterVersion(request: DeleteParameterVersionRequest) async throws {
    try await self.deleteParameterVersion(request: request, options: .init())
  }

  public func deleteParameterVersion(
    request: DeleteParameterVersionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteParameterVersion(
    name: Swift.String,
  ) async throws {
    let request = DeleteParameterVersionRequest().with {
      $0.name = name
    }
    try await self.deleteParameterVersion(request: request)
  }

  public func listTemplates(request: ListTemplatesRequest) async throws
    -> GoogleCloudParameterManagerV1.ListTemplatesResponse
  {
    try await self.listTemplates(request: request, options: .init())
  }

  public func listTemplates(
    request: ListTemplatesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listTemplates(
    byItem: ListTemplatesRequest
  ) throws -> any AsyncSequence<Template, Swift.Error> {
    try self.listTemplates(byItem: byItem, options: .init())
  }

  public func listTemplates(
    byItem: ListTemplatesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<Template, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTemplates(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Template, Swift.Error> {
    let request = ListTemplatesRequest().with {
      $0.parent = parent
    }
    return try self.listTemplates(byItem: request)
  }

  public func getTemplate(request: GetTemplateRequest) async throws
    -> GoogleCloudParameterManagerV1.Template
  {
    try await self.getTemplate(request: request, options: .init())
  }

  public func getTemplate(
    request: GetTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getTemplate(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    let request = GetTemplateRequest().with {
      $0.name = name
    }
    return try await self.getTemplate(request: request)
  }

  public func createTemplate(request: CreateTemplateRequest) async throws
    -> GoogleCloudParameterManagerV1.Template
  {
    try await self.createTemplate(request: request, options: .init())
  }

  public func createTemplate(
    request: CreateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createTemplate(
    parent: Swift.String,
    template: Template?,
    templateId: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    let request = CreateTemplateRequest().with {
      $0.parent = parent
      $0.template = template
      $0.templateId = templateId
    }
    return try await self.createTemplate(request: request)
  }

  public func updateTemplate(request: UpdateTemplateRequest) async throws
    -> GoogleCloudParameterManagerV1.Template
  {
    try await self.updateTemplate(request: request, options: .init())
  }

  public func updateTemplate(
    request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateTemplate(
    template: Template?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleCloudParameterManagerV1.Template {
    let request = UpdateTemplateRequest().with {
      $0.template = template
      $0.updateMask = updateMask
    }
    return try await self.updateTemplate(request: request)
  }

  public func deleteTemplate(request: DeleteTemplateRequest) async throws {
    try await self.deleteTemplate(request: request, options: .init())
  }

  public func deleteTemplate(
    request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteTemplate(
    name: Swift.String,
  ) async throws {
    let request = DeleteTemplateRequest().with {
      $0.name = name
    }
    try await self.deleteTemplate(request: request)
  }

  public func listTemplateVersions(request: ListTemplateVersionsRequest) async throws
    -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse
  {
    try await self.listTemplateVersions(request: request, options: .init())
  }

  public func listTemplateVersions(
    request: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listTemplateVersions(
    byItem: ListTemplateVersionsRequest
  ) throws -> any AsyncSequence<TemplateVersion, Swift.Error> {
    try self.listTemplateVersions(byItem: byItem, options: .init())
  }

  public func listTemplateVersions(
    byItem: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<TemplateVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTemplateVersions(
    parent: Swift.String,
  ) throws -> any AsyncSequence<TemplateVersion, Swift.Error> {
    let request = ListTemplateVersionsRequest().with {
      $0.parent = parent
    }
    return try self.listTemplateVersions(byItem: request)
  }

  public func getTemplateVersion(request: GetTemplateVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.TemplateVersion
  {
    try await self.getTemplateVersion(request: request, options: .init())
  }

  public func getTemplateVersion(
    request: GetTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getTemplateVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    let request = GetTemplateVersionRequest().with {
      $0.name = name
    }
    return try await self.getTemplateVersion(request: request)
  }

  public func createTemplateVersion(request: CreateTemplateVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.TemplateVersion
  {
    try await self.createTemplateVersion(request: request, options: .init())
  }

  public func createTemplateVersion(
    request: CreateTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createTemplateVersion(
    parent: Swift.String,
    templateVersion: TemplateVersion?,
    templateVersionId: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    let request = CreateTemplateVersionRequest().with {
      $0.parent = parent
      $0.templateVersion = templateVersion
      $0.templateVersionId = templateVersionId
    }
    return try await self.createTemplateVersion(request: request)
  }

  public func updateTemplateVersion(request: UpdateTemplateVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.TemplateVersion
  {
    try await self.updateTemplateVersion(request: request, options: .init())
  }

  public func updateTemplateVersion(
    request: UpdateTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateTemplateVersion(
    templateVersion: TemplateVersion?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
    let request = UpdateTemplateVersionRequest().with {
      $0.templateVersion = templateVersion
      $0.updateMask = updateMask
    }
    return try await self.updateTemplateVersion(request: request)
  }

  public func deleteTemplateVersion(request: DeleteTemplateVersionRequest) async throws {
    try await self.deleteTemplateVersion(request: request, options: .init())
  }

  public func deleteTemplateVersion(
    request: DeleteTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteTemplateVersion(
    name: Swift.String,
  ) async throws {
    let request = DeleteTemplateVersionRequest().with {
      $0.name = name
    }
    try await self.deleteTemplateVersion(request: request)
  }

  public func renderTemplateVersion(request: RenderTemplateVersionRequest) async throws
    -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse
  {
    try await self.renderTemplateVersion(request: request, options: .init())
  }

  public func renderTemplateVersion(
    request: RenderTemplateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func renderTemplateVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse {
    let request = RenderTemplateVersionRequest().with {
      $0.name = name
    }
    return try await self.renderTemplateVersion(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }
}
