// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ParameterManagerRetry: ParameterManagerStub {
    let inner: any ParameterManagerStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any ParameterManagerStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listParameters(
      request: ListParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListParametersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListParametersResponse
          in
          return try await self.inner.listParameters(request: r, options: o)
        })
    }

    public func getParameter(
      request: GetParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetParameterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.getParameter(request: r, options: o)
        })
    }

    public func createParameter(
      request: CreateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateParameterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.createParameter(request: r, options: o)
        })
    }

    public func updateParameter(
      request: UpdateParameterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateParameterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Parameter
          in
          return try await self.inner.updateParameter(request: r, options: o)
        })
    }

    public func deleteParameter(
      request: DeleteParameterRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteParameterRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteParameter(request: r, options: o)
        })
    }

    public func listParameterVersions(
      request: ListParameterVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListParameterVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse
          in
          return try await self.inner.listParameterVersions(request: r, options: o)
        })
    }

    public func getParameterVersion(
      request: GetParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.getParameterVersion(request: r, options: o)
        })
    }

    public func renderParameterVersion(
      request: RenderParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: RenderParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse
          in
          return try await self.inner.renderParameterVersion(request: r, options: o)
        })
    }

    public func createParameterVersion(
      request: CreateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.createParameterVersion(request: r, options: o)
        })
    }

    public func updateParameterVersion(
      request: UpdateParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateParameterVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ParameterVersion
          in
          return try await self.inner.updateParameterVersion(request: r, options: o)
        })
    }

    public func deleteParameterVersion(
      request: DeleteParameterVersionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteParameterVersionRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteParameterVersion(request: r, options: o)
        })
    }

    public func listTemplates(
      request: ListTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTemplatesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListTemplatesResponse
          in
          return try await self.inner.listTemplates(request: r, options: o)
        })
    }

    public func getTemplate(
      request: GetTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Template
          in
          return try await self.inner.getTemplate(request: r, options: o)
        })
    }

    public func createTemplate(
      request: CreateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Template
          in
          return try await self.inner.createTemplate(request: r, options: o)
        })
    }

    public func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.Template
          in
          return try await self.inner.updateTemplate(request: r, options: o)
        })
    }

    public func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteTemplateRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTemplate(request: r, options: o)
        })
    }

    public func listTemplateVersions(
      request: ListTemplateVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTemplateVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.ListTemplateVersionsResponse
          in
          return try await self.inner.listTemplateVersions(request: r, options: o)
        })
    }

    public func getTemplateVersion(
      request: GetTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.TemplateVersion
          in
          return try await self.inner.getTemplateVersion(request: r, options: o)
        })
    }

    public func createTemplateVersion(
      request: CreateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.TemplateVersion
          in
          return try await self.inner.createTemplateVersion(request: r, options: o)
        })
    }

    public func updateTemplateVersion(
      request: UpdateTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.TemplateVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.TemplateVersion
          in
          return try await self.inner.updateTemplateVersion(request: r, options: o)
        })
    }

    public func deleteTemplateVersion(
      request: DeleteTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTemplateVersion(request: r, options: o)
        })
    }

    public func renderTemplateVersion(
      request: RenderTemplateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: RenderTemplateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudParameterManagerV1.RenderTemplateVersionResponse
          in
          return try await self.inner.renderTemplateVersion(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
