// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol ParameterManagerStub {
    func listParameters(
      request: ListParametersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParametersResponse

    func getParameter(
      request: GetParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    func createParameter(
      request: CreateParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    func updateParameter(
      request: UpdateParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.Parameter

    func deleteParameter(
      request: DeleteParameterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listParameterVersions(
      request: ListParameterVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ListParameterVersionsResponse

    func getParameterVersion(
      request: GetParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    func renderParameterVersion(
      request: RenderParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.RenderParameterVersionResponse

    func createParameterVersion(
      request: CreateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    func updateParameterVersion(
      request: UpdateParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudParameterManagerV1.ParameterVersion

    func deleteParameterVersion(
      request: DeleteParameterVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
