// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message describing RenderParameterVersionResponse resource
public struct RenderParameterVersionResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource identifier of a ParameterVersion in the format
  /// `projects/*/locations/*/parameters/*/versions/*`.
  public var parameterVersion: Swift.String = Swift.String()

  /// Payload content of a ParameterVersion resource.
  public var payload: ParameterVersionPayload? = nil

  /// Output only. Server generated rendered version of the user provided payload
  /// data (ParameterVersionPayload) which has substitutions of all (if any)
  /// references to a SecretManager SecretVersion resources. This substitution
  /// only works for a Parameter which is in JSON or YAML format.
  public var renderedPayload: Foundation.Data = Foundation.Data()

  /// Initialize a new instance of `RenderParameterVersionResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RenderParameterVersionResponse().with { $0.parameterVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.parametermanager.v1.RenderParameterVersionResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
